menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

excerpt_link: Read More
archive_date_format: MMM DD

blogrolls: 
- Hexo: http://coolshell.cn

widgets: 
- blogroll
- weibo

fancybox: true

duoshuo_shortname: vimerme

google_analytics:
favicon: /favicon.ico
