menu:
  Home: /
  Archives: /archives
  About: /about

excerpt_link: Read More
archive_date_format: MMM DD

widgets:
- archive
- category
- tagcloud
- recent_posts

fancybox: true

duoshuo_shortname: vimerme

google_analytics:
favicon: /favicon.ico
